server.port=${PORT:8080}

spring.datasource.url=jdbc:postgresql://dpg-d77mfrogjchc73d1daeg-a:5432/student_db_aosn
spring.datasource.username=student_db_aosn_user
spring.datasource.password=4wG06J8u1q8P07VlmB18GkG4PLFIa1i7

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.security.user.name=teacher
spring.security.user.password=teacher123
